#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

case "$(uname -m)" in
  x86_64)        ARCH="x86_64" ;;
  arm64|aarch64) ARCH="aarch64" ;;
esac

FLAKE_TARGET="${ARCH}-darwin"
export NIXPKGS_ALLOW_UNFREE=1

printf "%bBuilding %s (dry-run)...%b\n" "$YELLOW" "$FLAKE_TARGET" "$NC"
nh darwin build . --hostname "$FLAKE_TARGET" -- "$@"

printf "%bBuild complete!%b\n" "$GREEN" "$NC"
