#!/bin/sh -e

GREEN='\033[1;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

printf "%bCleaning old generations (keeping last 2)...%b\n" "$YELLOW" "$NC"
nh clean all --keep 2

printf "%bCleanup complete!%b\n" "$GREEN" "$NC"
